/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa;
import clases.conectar;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 * 
 *
 * @author Daniel Martínez
 */
public class TablasInventario extends javax.swing.JPanel {

    
    DefaultTableModel modeloTabla;
   
    conectar con = new conectar();

    /**
     * Creates new form TablasInventario
     * @throws java.sql.SQLException
     */
    public TablasInventario() throws SQLException{
        
        modeloTabla = new DefaultTableModel(null, getColumnas());
        setFilas();
        initComponents();
        
    }
    
    private String[] getColumnas(){
        String columna[] = new String[]{"id_producto", "nombre", "costo", "cantidad"};
        return columna;   
           
    }
    
    private void setFilas() throws SQLException{
        try {
            String sql = "SELECT id_produ"
                    + "cto, nombre, costo, cantidad FROM productos";
            PreparedStatement us = con.getConnection().prepareStatement(sql);
            
            ResultSet res = us.executeQuery();
            Object datos[] = new Object[4];
        while(res.next()){
            for (int i = 0; i<4; i++ ){
                datos[i] = res.getObject(i+1);    
            }
            modeloTabla.addRow(datos);
        }
        res.close();
        }   
        catch(SQLException ex){
            Logger.getLogger(TablasInventario.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

   
}
